before_script:
  - pip install poetry
  - poetry install --with dev

cache:
  paths:
    - /root/.cache

stages:
  - style
  - test
  - package

tests:
  stage: test
  parallel:
    matrix:
      - COMMAND: [ "py39" ]
        IMAGE: [ "3.9" ]
      - COMMAND: [ "py311" ]
        IMAGE: [ "3.11" ]
  image: python:$IMAGE
  script:
    - poetry run tox -e $COMMAND
  artifacts:
    paths:
      - test_output/
    expire_in: 1 day

ruff:
  image: python:3.11
  stage: style
  allow_failure: true
  script:
    - poetry run tox -e ruff

build:
  image: python:3.11
  stage: package
  script:
    - poetry build
  artifacts:
    paths:
      - dist/